name: Lint Backend Code

on: [push]

jobs:
  Code_Linting:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      working-directory: ./code
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8
    - name: Analysing the backend code with flake
      working-directory: ./code
      run: |
        flake8