name: Pylint Backend Code

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install backend dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        pip install pylint
    - name: Analysing the backend code with pylint
      run: |
        pylint --rcfile=pylint.conf `find backend/|grep .py$|xargs`
