name: Pytest Unit Tests
on: [push]

jobs:
  Unit_tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.10', '3.11']

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/test_requirements.txt
      - name: Run pytest unit tests
        run: |
          python -m pytest
