name: Pytest backend Unit Tests
on: [push]

jobs:
  Unit_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install backend dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r test_requirements.txt
      - name: Run pytest unit tests
        working-directory: ./backend
        run: |
          python -m pytest tests/
